#!/bin/bash - 
# vim:et:ft=sh:sts=2:sw=2

function spin_up() {
  hdparm -S 0 "$@"
  for i in "$@"; do
    # do some I/O to make sure disks are up
    dd if=$i of=/dev/null bs=4k count=10 >/dev/null 2>&1
  done
}

function spin_down() {
  hdparm -y "$@"
}

function power_down() {
  hdparm -Y "$@"
}

function get_status() {
  hdparm -C "$@"
}
